apiVersion: apps/v1
kind: Deployment
metadata:
  name: laurens-page
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laurens-page
  template:
    metadata:
      labels:
        app: laurens-page
    spec:
      containers:
      - name: laurens-page
        image: gcr.io/cit-262-group3/laurens-page
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: ".5"
            memory: "500Mi"
          requests:
            cpu: ".25"
            memory: "250Mi"
        livenessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: laurens-page-service
spec:
  selector:
    app: laurens-page
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: laurens-page-loadbalancer
spec:
  selector:
    app: laurens-page
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
   
